name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' 

      - name: Instalar dependências
        run: go mod download

      - name: Build da aplicação
        run: go build -v -o app

      - name: Verificar binário
        run: ls -lh ./app