name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' 

      - name: Instalar dependências
        run: go mod download

      - name: Build da aplicação
        run: go build -v -o app cmd/main.go 

      - name: Verificar binário
        run: ls -lh ./app

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Montar imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/food:latest .

      - name: Publicar imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/food:latest

        
      
      